// Generated by gencpp from file robot_action_msg/robot_acts.msg
// DO NOT EDIT!


#ifndef ROBOT_ACTION_MSG_MESSAGE_ROBOT_ACTS_H
#define ROBOT_ACTION_MSG_MESSAGE_ROBOT_ACTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_action_msg
{
template <class ContainerAllocator>
struct robot_acts_
{
  typedef robot_acts_<ContainerAllocator> Type;

  robot_acts_()
    : type(0)
    , gait(0)
    , action(0)  {
    }
  robot_acts_(const ContainerAllocator& _alloc)
    : type(0)
    , gait(0)
    , action(0)  {
  (void)_alloc;
    }



   typedef int32_t _type_type;
  _type_type type;

   typedef int32_t _gait_type;
  _gait_type gait;

   typedef int32_t _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::robot_action_msg::robot_acts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_action_msg::robot_acts_<ContainerAllocator> const> ConstPtr;

}; // struct robot_acts_

typedef ::robot_action_msg::robot_acts_<std::allocator<void> > robot_acts;

typedef boost::shared_ptr< ::robot_action_msg::robot_acts > robot_actsPtr;
typedef boost::shared_ptr< ::robot_action_msg::robot_acts const> robot_actsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_action_msg::robot_acts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_action_msg::robot_acts_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_action_msg::robot_acts_<ContainerAllocator1> & lhs, const ::robot_action_msg::robot_acts_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.gait == rhs.gait &&
    lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_action_msg::robot_acts_<ContainerAllocator1> & lhs, const ::robot_action_msg::robot_acts_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_action_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_action_msg::robot_acts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_action_msg::robot_acts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_action_msg::robot_acts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_action_msg::robot_acts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_action_msg::robot_acts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_action_msg::robot_acts_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_action_msg::robot_acts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69255ef4e15806c24e79c0d43c19a260";
  }

  static const char* value(const ::robot_action_msg::robot_acts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69255ef4e15806c2ULL;
  static const uint64_t static_value2 = 0x4e79c0d43c19a260ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_action_msg::robot_acts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_action_msg/robot_acts";
  }

  static const char* value(const ::robot_action_msg::robot_acts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_action_msg::robot_acts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 type\n"
"int32 gait\n"
"int32 action\n"
;
  }

  static const char* value(const ::robot_action_msg::robot_acts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_action_msg::robot_acts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.gait);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_acts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_action_msg::robot_acts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_action_msg::robot_acts_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "gait: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gait);
    s << indent << "action: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_ACTION_MSG_MESSAGE_ROBOT_ACTS_H
